#RUN: ansible-playbook playbook.yaml -K --extra-vars "ansible_user=USERNAME"

#Replace USERNAME with the name of the operating system user that will execute the playbook.

- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/main.yml

  # Roles to execute

  roles: 
    # instalar java 17
    - install-java

    - install-maven

    - install-docker

    - install-nodejs

    #Source: https://github.com/geerlingguy/ansible-role-mysql
    - {role: ansible-role-mysql,
        mysql_root_username: root,
        mysql_root_password: root,
        mysql_root_password_update: false
      }

  tasks:

  # Tasks to be executed

    # - name: Install Java 17
    #   become: true
    #   ansible.builtin.apt:
    #     name: openjdk-17-jdk
    #     state: present

    # - name: Install Maven
    #   become: true
    #   apt:
    #     name: maven
    #   ansible.builtin.apt: openjdk-17-jdk