---
# tasks file for install-nodejs
- name: Install GPG
  tags: nodejs, install, setup
  become: true
  ansible.builtin.apt:
    name: gnupg
    update_cache: yes
    state: present

- name: Install the gpg key for nodejs LTS
  become: true
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install NodeJS
  become: true
  tags: nodesjs, install
  ansible.builtin.apt:
    name: nodejs
    state: latest
