---
# tasks file for install-docker
- name: Install required system packages
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  become: true
  ansible.builtin.apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Update apt and install docker-compose
  become: true
  ansible.builtin.apt:
    name: docker-compose
    state: latest
    update_cache: true

# - name: Enable using Docker for current user (without requiring sudo)
#   become: true
#   ansible.builtin.shell: usermod -aG docker {{ ansible_user }}
#   args:
#     executable: /bin/bash

- name: Add current user to docker group (without requiring sudo)
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Restart Docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: restarted